### ISSUE TITLE
Add ghost navigation support.

### ISSUE THREAD

**Issue by ghost** [secondimpression/json-ghost#2]
Would like to have page support and possibly a search bar.  Page support and search bar could either be added to a sidebar (preferably left) or it could be added between description and posts in the center json layout.

If added to a sidebar it would have the similar json format also.

![screen shot 2015-05-31 at 10 37 05 pm](https://cloud.githubusercontent.com/assets/9308054/7997399/0b02fb22-0af2-11e5-85f9-04e481158700.png)

**Comment by pmgarman** [comment]
It's not too hard to add nav support, I just did this in my own fork.

Modify the default.hbs file > https://github.com/pmgarman/json-ghost/blob/master/default.hbs#L37-L39
Create a navigation partial > https://github.com/pmgarman/json-ghost/blob/master/partials/navigation.hbs
See it in action > https://so.much.pizza

**Comment by ghost** [comment]
Got it!  Thanks.
